version: '3.7'

services:
  frontend:
    build: .
    image: masha29/frontend:latest
    volumes:
      - ${PWD}:/app
      - /app/node_modules
    ports:
      - 3000:80
    environment:
      - CHOKIDAR_USEPOLLING=true